https:
  port: "8082"
  
api:
  name: "cqrs-order-details-sys-api"
  
mysql:
  host: ""
  port: ""
  user: ""
  password : ""
  database: ""
  customertable: "customer"
  ordertable: "order_header"
  orderlinestable: "order_lines"

retry:
  threshold: "1"
  ttl: "5"

  
keystore:
  keyPassword: "mule123"
  password: "mule123"
