https:
  port: "8082"
  
api:
  name: "cqrs-order-sys-api"
  
mysql:
  host: ""
  port: ""
  user: ""
  password : ""
  database: ""
  ordertable: "order_header"

retry:
  threshold: "1"
  ttl: "5"
  
keystore:
  keyPassword: "mule123"
  password: "mule123"
  alias: "sender"